---
- hosts: webserver
  tasks: 
    - name: Install httpd
      yum: pkg=httpd state=latest
      when: ansible_distribution == "RedHat"
    - name: Install Apache
      apt: pkg=apache2 state=latest
      when:  ansible_distribution == "Ubuntu"
    - name: Start httpd
      service: name=httpd state=started
      when: ansible_distribution == "RedHat"
    - name: Start Apache
      service: name=apache2 state=started
      when:  ansible_distribution == "Ubuntu"
