---
- hosts: webserver
  user: root
  tasks: 
    - name: Install httpd
      yum: pkg=httpd state=installed
    - name: Verify httpd Status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5

