---
- hosts: webserver
  user: root
#  become: true 
  vars:
    pack_name: httpd
    serv_name: httpd
  
  tasks:
    - name: Install {{pack_name}}
      yum: pkg={{pack_name}} state=installed
      notify: Restart HTTPD
    - name: Install telnet
      yum: pkg=telnet state=installed 
    - name: Copy httpd.conf
      copy: src=/root/ansible/v2/files/httpd.conf dest=/etc/httpd/conf/httpd.conf owner=apache group=apache mode=0644
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name={{serv_name}} state=restarted 
